In [1]:
import json
import pandas as pd
import numpy as np

import re

from sqlalchemy import create_engine
import psycopg2

from config import db_password

import time

In [2]:
#  Add the clean movie function that takes in the argument, "movie".
def clean_movie(movie):
    movie = dict(movie) # Create a non-destructive copy
    alt_titles = {}
    
    # Combine alternate titles into one list
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune-Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles

    # merge column names
    def change_column_name(old_name, new_name):
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
    change_column_name('Adaptation by', 'Writer(s)')
    change_column_name('Country of origin', 'Country')
    change_column_name('Directed by', 'Director')
    change_column_name('Distributed by', 'Distributor')
    change_column_name('Edited by', 'Editor(s)')
    change_column_name('Length', 'Running time')
    change_column_name('Original release', 'Release date')
    change_column_name('Music by', 'Composer(s)')
    change_column_name('Produced by', 'Producer(s)')
    change_column_name('Producer', 'Producer(s)')
    change_column_name('Productioncompanies ', 'Production company(s)')
    change_column_name('Productioncompany ', 'Production company(s)')
    change_column_name('Released', 'Release Date')
    change_column_name('Release Date', 'Release date')
    change_column_name('Screen story by', 'Writer(s)')
    change_column_name('Screenplay by', 'Writer(s)')
    change_column_name('Story by', 'Writer(s)')
    change_column_name('Theme music composer', 'Composer(s)')
    change_column_name('Written by', 'Writer(s)')

    return movie

In [3]:
# 1 Add the function that takes in three arguments;
# Wikipedia data, Kaggle metadata, and MovieLens rating data (from Kaggle)

def extract_transform_load(wiki_file, kaggle_file, ratings_file):
    # Read in the kaggle metadata and MovieLens ratings CSV files as Pandas DataFrames.
    kaggle_metadata = pd.read_csv("Data/movies_metadata.csv", low_memory=False)
    ratings = pd.read_csv("Data/ratings.csv")

    # Open and read the Wikipedia data JSON file.
    with open("Data/wikipedia-movies.json", mode='r') as file:
        wiki_movies_raw = json.load(file)
    
    # Write a list comprehension to filter out TV shows.
    wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and ('imdb_link' in movie)
                   and ('No. of episodes' not in movie)]

    # Write a list comprehension to iterate through the cleaned wiki movies list
    # and call the clean_movie function on each movie.
    clean_movies = [clean_movie(movie) for movie in wiki_movies]

    # Read in the cleaned movies list from Step 4 as a DataFrame.
    wiki_movies_df = pd.DataFrame(clean_movies)

    # Write a try-except block to catch errors while extracting the IMDb ID using a regular expression string and
    #  dropping any imdb_id duplicates. If there is an error, capture and print the exception.
    try:
        wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\d{7})')
        print(len(wiki_movies_df))
        wiki_movies_df.drop_duplicates(subset='imdb_id', inplace=True)
        print(len(wiki_movies_df))
        
    except:
        print("Error.")

    # Write a list comprehension to keep the columns that don't have null values from the wiki_movies_df DataFrame.
    wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]
    wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]

    # Create a variable that will hold the non-null values from the “Box office” column.
    box_office = wiki_movies_df['Box office'].dropna()
    
    # Convert the box office data created in Step 8 to string values using the lambda and join functions.
    box_office = box_office.apply(lambda x: ' '.join(x) if type(x) == list else x)

    # Write a regular expression to match the six elements of "form_one" of the box office data.
    form_one = r'\$\s*\d+\.?\d*\s*[mb]illi?on'
   
    # Write a regular expression to match the three elements of "form_two" of the box office data.
    form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)'

    # Add the parse_dollars function.
    def parse_dollars(s):
        # if s is not a string, return NaN
        if type(s) != str:
            return np.nan

        # if input is of the form $###.# million
        if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):

            # remove dollar sign and " million"
            s = re.sub('\$|\s|[a-zA-Z]','', s)

            # convert to float and multiply by a million
            value = float(s) * 10**6

            # return value
            return value

        # if input is of the form $###.# billion
        elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):

            # remove dollar sign and " billion"
            s = re.sub('\$|\s|[a-zA-Z]','', s)

            # convert to float and multiply by a billion
            value = float(s) * 10**9

            # return value
            return value

        # if input is of the form $###,###,###
        elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):

            # remove dollar sign and commas
            s = re.sub('\$|,','', s)

            # convert to float
            value = float(s)

            # return value
            return value

        # otherwise, return NaN
        else:
            return np.nan
        
    # Clean the box office column in the wiki_movies_df DataFrame.
    wiki_movies_df['box_office'] = box_office.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
    wiki_movies_df.drop('Box office', axis=1, inplace=True)
    
    
    
    # Clean the budget column in the wiki_movies_df DataFrame.
    # Create budget variable and drop null values.
    budget = wiki_movies_df['Budget'].dropna()

    # Convert any lists to strings.
    budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)

    # Remove values between a $ and a hyphen.
    budget = budget.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)
    
    # Form one and form two
    matches_form_one = budget.str.contains(form_one, flags=re.IGNORECASE, na=False)
    matches_form_two = budget.str.contains(form_two, flags=re.IGNORECASE, na=False)
    
    # Remove the citation references.
    budget = budget.str.replace(r'\[\d+\]\s*', '')
    
    # Create new column and remove old column.
    wiki_movies_df['budget'] = budget.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
    wiki_movies_df.drop('Budget', axis=1, inplace=True)

    
    
    # Clean the release date column in the wiki_movies_df DataFrame.
    # Create release_date variable and drop null values.
    release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
    
    # Parse the release_date data.
    date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s[123]?\d,\s\d{4}'
    date_form_two = r'\d{4}.[01]\d.[0123]\d'
    date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}'
    date_form_four = r'\d{4}'
    
    # Create new column and remove old column.
    wiki_movies_df['release_date'] = pd.to_datetime(release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})')[0], infer_datetime_format=True)
    wiki_movies_df.drop('Release date', axis=1, inplace=True)

    
    
    # Clean the running time column in the wiki_movies_df DataFrame.
    # Create a running_time variable and drop null values.
    running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
    
    # Create a capture group to extract running_time data.
    running_time_extract = running_time.str.extract(r'(\d+)\s*ho?u?r?s?\s*(\d*)|(\d+)\s*m')
    
    # Edit running_time_extract.
    running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)

    # Create new column and remove old column.
    wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)
    wiki_movies_df.drop('Running time', axis=1, inplace=True)
    
    
     
    # 2. Clean the Kaggle metadata.
    # Get false adult values and drop the original adult column.
    kaggle_metadata = kaggle_metadata[kaggle_metadata['adult'] == 'False'].drop('adult',axis='columns')

    # Get the true video values.
    kaggle_metadata['video'] = kaggle_metadata['video'] == 'True'
    
    # Make other adjustments for data types.
    kaggle_metadata['budget'] = kaggle_metadata['budget'].astype(int)
    kaggle_metadata['id'] = pd.to_numeric(kaggle_metadata['id'], errors='raise')
    kaggle_metadata['popularity'] = pd.to_numeric(kaggle_metadata['popularity'], errors='raise')
    kaggle_metadata['release_date'] = pd.to_datetime(kaggle_metadata['release_date'])

    # 3. Merged the two DataFrames into the movies DataFrame.
    movies_df = pd.merge(wiki_movies_df, kaggle_metadata, on='imdb_id', suffixes=['_wiki','_kaggle'])

    # 4. Drop unnecessary columns from the merged DataFrame.
    movies_df.drop(columns=['title_wiki','release_date_wiki','Language','Production company(s)'], inplace=True)

    # 5. Add in the function to fill in the missing Kaggle data.
    def fill_missing_kaggle_data(df, kaggle_column, wiki_column):
        df[kaggle_column] = df.apply(
            lambda row: row[wiki_column] if row[kaggle_column] == 0 else row[kaggle_column]
            , axis=1)
        df.drop(columns=wiki_column, inplace=True)

    # 6. Call the function in Step 5 with the DataFrame and columns as the arguments.
    fill_missing_kaggle_data(movies_df, 'runtime', 'running_time')
    fill_missing_kaggle_data(movies_df, 'budget_kaggle', 'budget_wiki')
    fill_missing_kaggle_data(movies_df, 'revenue', 'box_office')

    # 7. Filter the movies DataFrame for specific columns.
    movies_df = movies_df.loc[:, ['imdb_id','id','title_kaggle','original_title','tagline','belongs_to_collection','url','imdb_link',
                       'runtime','budget_kaggle','revenue','release_date_kaggle','popularity','vote_average','vote_count',
                       'genres','original_language','overview','spoken_languages','Country',
                       'production_companies','production_countries','Distributor',
                       'Producer(s)','Director','Starring','Cinematography','Editor(s)','Writer(s)','Composer(s)','Based on'
                      ]]

    # 8. Rename the columns in the movies DataFrame.
    movies_df.rename({'id':'kaggle_id',
                  'title_kaggle':'title',
                  'url':'wikipedia_url',
                  'budget_kaggle':'budget',
                  'release_date_kaggle':'release_date',
                  'Country':'country',
                  'Distributor':'distributor',
                  'Producer(s)':'producers',
                  'Director':'director',
                  'Starring':'starring',
                  'Cinematography':'cinematography',
                  'Editor(s)':'editors',
                  'Writer(s)':'writers',
                  'Composer(s)':'composers',
                  'Based on':'based_on'
                 }, axis='columns', inplace=True)

    # 9. Transform and merge the ratings DataFrame.
    # Convert the timestamp column to datetime.
    pd.to_datetime(ratings['timestamp'], unit='s')
    
    # Add the new timestamp column to the ratings data.
    ratings['timestamp'] = pd.to_datetime(ratings['timestamp'], unit='s')
    
    # Examine ratings data.
    rating_counts = ratings.groupby(['movieId','rating'], as_index=False).count() \
                    .rename({'userId':'count'}, axis=1) \
                    .pivot(index='movieId',columns='rating', values='count')
    
    # Use list comprehension to prepend rating_ to each column.
    rating_counts.columns = ['rating_' + str(col) for col in rating_counts.columns]
    
    # Merge movies_df with ratings.
    movies_with_ratings_df = pd.merge(movies_df, rating_counts, left_on='kaggle_id', right_index=True, how='left')
    
    # Fill in missing values with 0.
    movies_with_ratings_df[rating_counts.columns] = movies_with_ratings_df[rating_counts.columns].fillna(0)
    
    # Create connection string for the local server.
    db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/movie_data"
    
    # Create the database engine.
    engine = create_engine(db_string)
    
    # Import the movie data.
    movies_df.to_sql(name='movies', con=engine, if_exists='replace')
    
    # Import the ratings data and print the elapsed time.
    rows_imported = 0
    
    # get the start_time from time.time()
    start_time = time.time()
    
    for data in pd.read_csv('Data/ratings.csv', chunksize=1000000):
        print(f'importing rows {rows_imported} to {rows_imported + len(data)}...', end='')
        data.to_sql(name='ratings', con=engine, if_exists='append')
        rows_imported += len(data)

        # add elapsed time to final print out
        print(f'Done. {time.time() - start_time} total seconds elapsed')
        
    # Return three variables. The first is the wiki_movies_df DataFrame
    return wiki_movies_df, kaggle_metadata, ratings

In [4]:
# 10. Create the path to your file directory and variables for the three files.
# The Wikipedia data
wiki_file = 'Data/wikipedia.movies.json'
# The Kaggle metadata
kaggle_file = 'Data/movies_metadata.csv'
# The MovieLens rating data.
ratings_file = 'Data/ratings.csv'

In [5]:
# 11. Set the three variables equal to the function created in D1.
extract_transform_load(wiki_file, kaggle_file, ratings_file)

7076
7033

<ipython-input-3-2d11ca166b28>:120: FutureWarning: The default value of regex will change from True to False in a future version.
  budget = budget.str.replace(r'\[\d+\]\s*', '')

importing rows 0 to 1000000...Done. 18.71648621559143 total seconds elapsed
importing rows 1000000 to 2000000...Done. 37.31622505187988 total seconds elapsed
importing rows 2000000 to 3000000...Done. 56.51871204376221 total seconds elapsed
importing rows 3000000 to 4000000...Done. 75.32911610603333 total seconds elapsed
importing rows 4000000 to 5000000...Done. 93.68340706825256 total seconds elapsed
importing rows 5000000 to 6000000...Done. 112.05827617645264 total seconds elapsed
importing rows 6000000 to 7000000...Done. 130.66900086402893 total seconds elapsed
importing rows 7000000 to 8000000...Done. 149.30047011375427 total seconds elapsed
importing rows 8000000 to 9000000...Done. 168.4997420310974 total seconds elapsed
importing rows 9000000 to 10000000...Done. 187.92931509017944 total seconds elapsed
importing rows 10000000 to 11000000...Done. 207.1291000843048 total seconds elapsed
importing rows 11000000 to 12000000...Done. 225.90016412734985 total seconds elapsed
importing rows 12000000 to 13000000...Done. 244.7884931564331 total seconds elapsed
importing rows 13000000 to 14000000...Done. 264.1701970100403 total seconds elapsed
importing rows 14000000 to 15000000...Done. 282.7564878463745 total seconds elapsed
importing rows 15000000 to 16000000...Done. 301.43232798576355 total seconds elapsed
importing rows 16000000 to 17000000...Done. 320.85034012794495 total seconds elapsed
importing rows 17000000 to 18000000...Done. 339.5256929397583 total seconds elapsed
importing rows 18000000 to 19000000...Done. 358.3026440143585 total seconds elapsed
importing rows 19000000 to 20000000...Done. 377.4277181625366 total seconds elapsed
importing rows 20000000 to 21000000...Done. 396.34302520751953 total seconds elapsed
importing rows 21000000 to 22000000...Done. 415.5543830394745 total seconds elapsed
importing rows 22000000 to 23000000...Done. 434.5404050350189 total seconds elapsed
importing rows 23000000 to 24000000...Done. 453.4450418949127 total seconds elapsed
importing rows 24000000 to 25000000...Done. 472.1186361312866 total seconds elapsed
importing rows 25000000 to 26000000...Done. 490.80647706985474 total seconds elapsed
importing rows 26000000 to 26024289...Done. 491.2182688713074 total seconds elapsed

(                                                    url  year  \
 0     https://en.wikipedia.org/wiki/The_Adventures_o...  1990
 1     https://en.wikipedia.org/wiki/After_Dark,_My_S...  1990
 2      https://en.wikipedia.org/wiki/Air_America_(film)  1990
 3       https://en.wikipedia.org/wiki/Alice_(1990_film)  1990
 4         https://en.wikipedia.org/wiki/Almost_an_Angel  1990
 ...                                                 ...   ...
 7071    https://en.wikipedia.org/wiki/Holmes_%26_Watson  2018
 7072     https://en.wikipedia.org/wiki/Vice_(2018_film)  2018
 7073  https://en.wikipedia.org/wiki/On_the_Basis_of_Sex  2018
 7074  https://en.wikipedia.org/wiki/Destroyer_(2018_...  2018
 7075  https://en.wikipedia.org/wiki/Black_Mirror:_Ba...  2018

                                   imdb_link                            title  \
 0     https://www.imdb.com/title/tt0098987/  The Adventures of Ford Fairlane
 1     https://www.imdb.com/title/tt0098994/             After Dark, My Sweet
 2     https://www.imdb.com/title/tt0099005/                      Air America
 3     https://www.imdb.com/title/tt0099012/                            Alice
 4     https://www.imdb.com/title/tt0099018/                  Almost an Angel
 ...                                     ...                              ...
 7071  https://www.imdb.com/title/tt1255919/                  Holmes & Watson
 7072  https://www.imdb.com/title/tt6266538/                             Vice
 7073  https://www.imdb.com/title/tt4669788/              On the Basis of Sex
 7074  https://www.imdb.com/title/tt7137380/                        Destroyer
 7075  https://www.imdb.com/title/tt9495224/                     Bandersnatch

                                                Based on  \
 0                           [Characters, by Rex Weiner]
 1     [the novel, After Dark, My Sweet, by, Jim Thom...
 2                [Air America, by, Christopher Robbins]
 3                                                   NaN
 4                                                   NaN
 ...                                                 ...
 7071  [Sherlock Holmes, and, Dr. Watson, by, Sir Art...
 7072                                                NaN
 7073                                                NaN
 7074                                                NaN
 7075                                                NaN

                                                Starring  \
 0     [Andrew Dice Clay, Wayne Newton, Priscilla Pre...
 1     [Jason Patric, Rachel Ward, Bruce Dern, George...
 2     [Mel Gibson, Robert Downey Jr., Nancy Travis, ...
 3     [Alec Baldwin, Blythe Danner, Judy Davis, Mia ...
 4           [Paul Hogan, Elias Koteas, Linda Kozlowski]
 ...                                                 ...
 7071  [Will Ferrell, John C. Reilly, Rebecca Hall, R...
 7072  [Christian Bale, Amy Adams, Steve Carell, Sam ...
 7073  [Felicity Jones, Armie Hammer, Justin Theroux,...
 7074  [Nicole Kidman, Sebastian Stan, Toby Kebbell, ...
 7075  [Fionn Whitehead, Will Poulter, Craig Parkinso...

                      Cinematography         Country        Language  \
 0                       Oliver Wood   United States         English
 1                      Mark Plummer   United States         English
 2                     Roger Deakins   United States  [English, Lao]
 3                    Carlo Di Palma   United States         English
 4                      Russell Boyd              US         English
 ...                             ...             ...             ...
 7071                    Oliver Wood   United States         English
 7072                   Greig Fraser   United States         English
 7073                  Michael Grady   United States         English
 7074                 Julie Kirkwood   United States         English
 7075  [Aaron Morton, Jake Polonsky]  United Kingdom         English

                 Director  ...                       Editor(s)  \
 0           Renny Harlin  ...                 Michael Tronick
 1            James Foley  ...                 Howard E. Smith
 2     Roger Spottiswoode  ...  [John Bloom, Lois Freeman-Fox]
 3            Woody Allen  ...                  Susan E. Morse
 4           John Cornell  ...                    David Stiven
 ...                  ...  ...                             ...
 7071          Etan Cohen  ...                  Dean Zimmerman
 7072          Adam McKay  ...                     Hank Corwin
 7073          Mimi Leder  ...                 Michelle Tesoro
 7074        Karyn Kusama  ...                   Plummy Tucker
 7075         David Slade  ...                     Tony Kearns

                   Composer(s)  \
 0     [Cliff Eidelman, Yello]
 1               Maurice Jarre
 2               Charles Gross
 3                         NaN
 4               Maurice Jarre
 ...                       ...
 7071        Mark Mothersbaugh
 7072         Nicholas Britell
 7073            Mychael Danna
 7074         Theodore Shapiro
 7075           Brian Reitzell

                                             Producer(s)  \
 0                            [Steve Perry, Joel Silver]
 1                           [Ric Kidney, Robert Redlin]
 2                                        Daniel Melnick
 3                                       Robert Greenhut
 4                                          John Cornell
 ...                                                 ...
 7071  [Will Ferrell, Adam McKay, Jimmy Miller, Clayt...
 7072  [Brad Pitt, Dede Gardner, Jeremy Kleiner, Kevi...
 7073                                     Robert W. Cort
 7074             [Fred Berger, Phil Hay, Matt Manfredi]
 7075                                     Russell McLean

                                   Production company(s)  \
 0                                       Silver Pictures
 1                                       Avenue Pictures
 2                 [Carolco Pictures, IndieProd Company]
 3                                                   NaN
 4                                                   NaN
 ...                                                 ...
 7071  [Columbia Pictures, Gary Sanchez Productions, ...
 7072  [Plan B Entertainment, Gary Sanchez Production...
 7073  [Focus Features, [1], Participant Media, [1], ...
 7074  [30West, Automatik Entertainment, Annapurna Pi...
 7075                       [House of Tomorrow, Netflix]

                          Writer(s)    imdb_id  box_office      budget  \
 0      [David Arnott, James Cappe]  tt0098987  21400000.0  20000000.0
 1     [James Foley, Robert Redlin]  tt0098994   2700000.0   6000000.0
 2       [John Eskow, Richard Rush]  tt0099005  57718089.0  35000000.0
 3                      Woody Allen  tt0099012   7331647.0  12000000.0
 4                       Paul Hogan  tt0099018   6939946.0  25000000.0
 ...                            ...        ...         ...         ...
 7071                    Etan Cohen  tt1255919  41900000.0  42000000.0
 7072                    Adam McKay  tt6266538  76100000.0  60000000.0
 7073             Daniel Stiepleman  tt4669788  38400000.0  20000000.0
 7074     [Phil Hay, Matt Manfredi]  tt7137380   5500000.0   9000000.0
 7075               Charlie Brooker  tt9495224         NaN         NaN

       release_date running_time
 0       1990-07-11        102.0
 1       1990-05-17        114.0
 2       1990-08-10        113.0
 3       1990-12-25        106.0
 4       1990-12-19         95.0
 ...            ...          ...
 7071    2018-12-25         90.0
 7072    2018-12-11        132.0
 7073    2018-11-08        120.0
 7074    2018-08-31        123.0
 7075    2018-12-01         90.0

 [7033 rows x 21 columns],
                                    belongs_to_collection    budget  \
 0      {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
 1                                                    NaN  65000000
 2      {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
 3                                                    NaN  16000000
 4      {'id': 96871, 'name': 'Father of the Bride Col...         0
 ...                                                  ...       ...
 45461                                                NaN         0
 45462                                                NaN         0
 45463                                                NaN         0
 45464                                                NaN         0
 45465                                                NaN         0

                                                   genres  \
 0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
 1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
 2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
 3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
 4                         [{'id': 35, 'name': 'Comedy'}]
 ...                                                  ...
 45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
 45462                      [{'id': 18, 'name': 'Drama'}]
 45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
 45464                                                 []
 45465                                                 []

                                    homepage      id    imdb_id  \
 0      http://toystory.disney.com/toy-story     862  tt0114709
 1                                       NaN    8844  tt0113497
 2                                       NaN   15602  tt0113228
 3                                       NaN   31357  tt0114885
 4                                       NaN   11862  tt0113041
 ...                                     ...     ...        ...
 45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470
 45462                                   NaN  111109  tt2028550
 45463                                   NaN   67758  tt0303758
 45464                                   NaN  227506  tt0008536
 45465                                   NaN  461257  tt6980792

       original_language               original_title  \
 0                    en                    Toy Story
 1                    en                      Jumanji
 2                    en             Grumpier Old Men
 3                    en            Waiting to Exhale
 4                    en  Father of the Bride Part II
 ...                 ...                          ...
 45461                fa                      رگ خواب
 45462                tl          Siglo ng Pagluluwal
 45463                en                     Betrayal
 45464                en          Satana likuyushchiy
 45465                en                     Queerama

                                                 overview  popularity  ...  \
 0      Led by Woody, Andy's toys live happily in his ...   21.946943  ...
 1      When siblings Judy and Peter discover an encha...   17.015539  ...
 2      A family wedding reignites the ancient feud be...   11.712900  ...
 3      Cheated on, mistreated and stepped on, the wom...    3.859495  ...
 4      Just when George Banks has recovered from his ...    8.387519  ...
 ...                                                  ...         ...  ...
 45461        Rising and falling between a man and woman.    0.072051  ...
 45462  An artist struggles to finish his work while a...    0.178241  ...
 45463  When one of her hits goes wrong, a professiona...    0.903007  ...
 45464  In a small town live two brothers, one a minis...    0.003503  ...
 45465  50 years after decriminalisation of homosexual...    0.163015  ...

       release_date      revenue runtime  \
 0       1995-10-30  373554033.0    81.0
 1       1995-12-15  262797249.0   104.0
 2       1995-12-22          0.0   101.0
 3       1995-12-22   81452156.0   127.0
 4       1995-02-10   76578911.0   106.0
 ...            ...          ...     ...
 45461          NaT          0.0    90.0
 45462   2011-11-17          0.0   360.0
 45463   2003-08-01          0.0    90.0
 45464   1917-10-21          0.0    87.0
 45465   2017-06-09          0.0    75.0

                                         spoken_languages    status  \
 0               [{'iso_639_1': 'en', 'name': 'English'}]  Released
 1      [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released
 2               [{'iso_639_1': 'en', 'name': 'English'}]  Released
 3               [{'iso_639_1': 'en', 'name': 'English'}]  Released
 4               [{'iso_639_1': 'en', 'name': 'English'}]  Released
 ...                                                  ...       ...
 45461             [{'iso_639_1': 'fa', 'name': 'فارسی'}]  Released
 45462                  [{'iso_639_1': 'tl', 'name': ''}]  Released
 45463           [{'iso_639_1': 'en', 'name': 'English'}]  Released
 45464                                                 []  Released
 45465           [{'iso_639_1': 'en', 'name': 'English'}]  Released

                                                  tagline  \
 0                                                    NaN
 1              Roll the dice and unleash the excitement!
 2      Still Yelling. Still Fighting. Still Ready for...
 3      Friends are the people who let you be yourself...
 4      Just When His World Is Back To Normal... He's ...
 ...                                                  ...
 45461         Rising and falling between a man and woman
 45462                                                NaN
 45463                             A deadly game of wits.
 45464                                                NaN
 45465                                                NaN

                              title  video vote_average vote_count
 0                        Toy Story  False          7.7     5415.0
 1                          Jumanji  False          6.9     2413.0
 2                 Grumpier Old Men  False          6.5       92.0
 3                Waiting to Exhale  False          6.1       34.0
 4      Father of the Bride Part II  False          5.7      173.0
 ...                            ...    ...          ...        ...
 45461                       Subdue  False          4.0        1.0
 45462          Century of Birthing  False          9.0        3.0
 45463                     Betrayal  False          3.8        6.0
 45464             Satan Triumphant  False          0.0        0.0
 45465                     Queerama  False          0.0        0.0

 [45454 rows x 23 columns],
           userId  movieId  rating           timestamp
 0              1      110     1.0 2015-03-09 22:52:09
 1              1      147     4.5 2015-03-09 23:07:15
 2              1      858     5.0 2015-03-09 22:52:03
 3              1     1221     5.0 2015-03-09 22:52:26
 4              1     1246     5.0 2015-03-09 22:52:36
 ...          ...      ...     ...                 ...
 26024284  270896    58559     5.0 2009-10-31 23:26:04
 26024285  270896    60069     5.0 2009-10-31 23:33:52
 26024286  270896    63082     4.5 2009-10-31 23:29:24
 26024287  270896    64957     4.5 2009-11-01 00:06:30
 26024288  270896    71878     2.0 2009-10-31 23:30:58

 [26024289 rows x 4 columns])

In [6]:
# 12. Set the DataFrames from the return statement equal to the file names in Step 11. 
wiki_movies_df = wiki_file
movies_with_ratings_df = kaggle_file
movies_df = ratings_file

In [7]:
# 13. Check the wiki_movies_df DataFrame. 
wiki_movies_df.head()

AttributeError: 'str' object has no attribute 'head'

In [ ]:
# 14. Check the movies_with_ratings_df DataFrame.
movies_with_ratings_df.head()

In [ ]:
# 15. Check the movies_df DataFrame. 
movies_df.head()